### PR TITLE
Enable Sentry Caches and Queries pages

### PR DESCRIPTION
**Pull request by ouziel-slama**
* [x] Double-check the spelling and grammar of all strings, code comments, etc.
* [x] Double-check that all code is deterministic that needs to be
* [x] Add tests to cover any new or revised logic
* [x] Ensure that the test suite passes
* [x] Update the project [release notes](release-notes/)
* [x] Update the project documentation, as appropriate, with a corresponding Pull Request in the [Documentation repository](https://github.com/CounterpartyXCP/Documentation)

### CODE REVIEW

**Review by adamkrellenstein — APPROVED** [review]

**Comment by ouziel-slama** [comment]
Need to be tested after the Aug 24th.

**Comment by adamkrellenstein** [comment]
Can we also add a Sentry tag for mainnet/testnet?

**Comment by adamkrellenstein** [comment]
What's the status of this?

**Comment by ouziel-slama** [comment]
moved here https://github.com/CounterpartyXCP/counterparty-core/pull/2318

**Pull request closed without merging**
