### PR TITLE
Basic counterparty-server and bitcoin core client

### PR DESCRIPTION
**Pull request by ouziel-slama**
```
$ python3 tools/xcpcli.py -h
usage: xcpcli [-h]
              {get_blocks,get_last_block,get_block_by_height,get_block_by_hash,get_transactions_by_block,get_events_by_block,get_event_counts_by_block,get_events_by_block_and_event,get_credits_by_block,get_debits_by_block,get_expirations,get_cancels,get_destructions,get_issuances_by_block,get_sends_by_block,get_dispenses_by_block,get_sweeps_by_block,get_transactions,info,unpack,get_transaction_by_tx_index,get_transaction_by_hash,get_events_by_transaction_index,get_events_by_transaction_hash,get_sends_by_transaction_hash,get_dispenses_by_transaction_hash,get_events_by_transaction_index_and_event,get_events_by_transaction_hash_and_event,get_balances_by_addresses,get_transactions_by_addresses,get_events_by_addresses,get_mempool_events_by_addresses,get_address_balances,get_balance_by_address_and_asset,get_credits_by_address,get_debits_by_address,get_bet_by_feed,get_broadcasts_by_source,get_burns_by_address,get_sends_by_address,get_receive_by_address,get_sends_by_address_and_asset,get_receive_by_address_and_asset,get_dispensers_by_address,get_dispenser_by_address_and_asset,get_dispenses_by_source,get_dispenses_by_destination,get_dispenses_by_source_and_asset,get_dispenses_by_destination_and_asset,get_sweeps_by_address,get_issuances_by_address,get_valid_assets_by_issuer,get_transactions_by_address,get_dividends_distributed_by_address,get_orders_by_address,get_fairminters_by_address,get_fairmints_by_address,get_fairmints_by_address_and_asset,compose_bet,compose_broadcast,compose_btcpay,compose_burn,compose_cancel,compose_destroy,compose_dispenser,compose_dividend,compose_issuance,compose_mpma,compose_order,compose_send,compose_sweep,compose_dispense,compose_fairminter,compose_fairmint,compose_attach,compose_detach,compose_movetoutxo,get_valid_assets,get_asset,get_asset_balances,get_orders_by_asset,get_order_matches_by_asset,get_credits_by_asset,get_debits_by_asset,get_dividends_by_asset,get_issuances_by_asset,get_sends_by_asset,get_dispensers_by_asset,get_asset_holders,get_dispenses_by_asset,get_subassets_by_asset,get_fairminters_by_asset,get_fairmints_by_asset,get_orders,get_order,get_order_matches_by_order,get_btcpays_by_order,get_orders_by_two_assets,get_order_matches_by_two_assets,get_all_order_matches,get_bets,get_bet,get_bet_matches_by_bet,get_resolutions_by_bet,get_all_burns,get_dispensers,get_dispenser_info_by_hash,get_dispenses_by_dispenser,get_dividends,get_dividend,get_dividend_disribution,get_all_events,get_event_by_index,get_all_events_counts,get_events_by_name,get_event_count,get_dispenses,get_sends,get_issuances,get_issuance_by_transaction_hash,get_sweeps,get_sweep_by_transaction_hash,get_valid_broadcasts,get_broadcast_by_transaction_hash,get_all_fairminters,get_fairminter,get_fairmints_by_fairminter,get_unspent_txouts_by_addresses,get_oldest_transaction_by_address,get_unspent_txouts,pubkeyhash_to_pubkey,get_transaction,fee_per_kb,sendrawtransaction,get_all_mempool_events,get_mempool_events_by_name,get_mempool_events_by_tx_hash,get_routes,check_server_health,send_bet,send_broadcast,send_btcpay,send_burn,send_cancel,send_destroy,send_dispenser,send_dividend,send_issuance,send_mpma,send_order,send_send,send_sweep,send_dispense,send_fairminter,send_fairmint,send_attach,send_detach,send_movetoutxo}
              ...

A basic counterparty-server and Bitcoin Core client

positional arguments:
  {get_blocks,get_last_block,get_block_by_height,get_block_by_hash,get_transactions_by_block,get_events_by_block,get_event_counts_by_block,get_events_by_block_and_event,get_credits_by_block,get_debits_by_block,get_expirations,get_cancels,get_destructions,get_issuances_by_block,get_sends_by_block,get_dispenses_by_block,get_sweeps_by_block,get_transactions,info,unpack,get_transaction_by_tx_index,get_transaction_by_hash,get_events_by_transaction_index,get_events_by_transaction_hash,get_sends_by_transaction_hash,get_dispenses_by_transaction_hash,get_events_by_transaction_index_and_event,get_events_by_transaction_hash_and_event,get_balances_by_addresses,get_transactions_by_addresses,get_events_by_addresses,get_mempool_events_by_addresses,get_address_balances,get_balance_by_address_and_asset,get_credits_by_address,get_debits_by_address,get_bet_by_feed,get_broadcasts_by_source,get_burns_by_address,get_sends_by_address,get_receive_by_address,get_sends_by_address_and_asset,get_receive_by_address_and_asset,get_dispensers_by_address,get_dispenser_by_address_and_asset,get_dispenses_by_source,get_dispenses_by_destination,get_dispenses_by_source_and_asset,get_dispenses_by_destination_and_asset,get_sweeps_by_address,get_issuances_by_address,get_valid_assets_by_issuer,get_transactions_by_address,get_dividends_distributed_by_address,get_orders_by_address,get_fairminters_by_address,get_fairmints_by_address,get_fairmints_by_address_and_asset,compose_bet,compose_broadcast,compose_btcpay,compose_burn,compose_cancel,compose_destroy,compose_dispenser,compose_dividend,compose_issuance,compose_mpma,compose_order,compose_send,compose_sweep,compose_dispense,compose_fairminter,compose_fairmint,compose_attach,compose_detach,compose_movetoutxo,get_valid_assets,get_asset,get_asset_balances,get_orders_by_asset,get_order_matches_by_asset,get_credits_by_asset,get_debits_by_asset,get_dividends_by_asset,get_issuances_by_asset,get_sends_by_asset,get_dispensers_by_asset,get_asset_holders,get_dispenses_by_asset,get_subassets_by_asset,get_fairminters_by_asset,get_fairmints_by_asset,get_orders,get_order,get_order_matches_by_order,get_btcpays_by_order,get_orders_by_two_assets,get_order_matches_by_two_assets,get_all_order_matches,get_bets,get_bet,get_bet_matches_by_bet,get_resolutions_by_bet,get_all_burns,get_dispensers,get_dispenser_info_by_hash,get_dispenses_by_dispenser,get_dividends,get_dividend,get_dividend_disribution,get_all_events,get_event_by_index,get_all_events_counts,get_events_by_name,get_event_count,get_dispenses,get_sends,get_issuances,get_issuance_by_transaction_hash,get_sweeps,get_sweep_by_transaction_hash,get_valid_broadcasts,get_broadcast_by_transaction_hash,get_all_fairminters,get_fairminter,get_fairmints_by_fairminter,get_unspent_txouts_by_addresses,get_oldest_transaction_by_address,get_unspent_txouts,pubkeyhash_to_pubkey,get_transaction,fee_per_kb,sendrawtransaction,get_all_mempool_events,get_mempool_events_by_name,get_mempool_events_by_tx_hash,get_routes,check_server_health,send_bet,send_broadcast,send_btcpay,send_burn,send_cancel,send_destroy,send_dispenser,send_dividend,send_issuance,send_mpma,send_order,send_send,send_sweep,send_dispense,send_fairminter,send_fairmint,send_attach,send_detach,send_movetoutxo}
                        the API call to make
    get_blocks          Returns the list of the last ten blocks
    get_last_block      Return the information of the last block
    get_block_by_height
                        Return the information of a block
    get_block_by_hash   Return the information of a block
    get_transactions_by_block
                        Returns the transactions of a block
    get_events_by_block
                        Returns the events of a block
    get_event_counts_by_block
                        Returns the event counts of a block
    get_events_by_block_and_event
                        Returns the events of a block filtered by event
    get_credits_by_block
                        Returns the credits of a block
    get_debits_by_block
                        Returns the debits of a block
    get_expirations     Returns the expirations of a block
    get_cancels         Returns the cancels of a block
    get_destructions    Returns the destructions of a block
    get_issuances_by_block
                        Returns the issuances of a block
    get_sends_by_block  Returns the sends, include Enhanced and MPMA sends, of a block
    get_dispenses_by_block
                        Returns the dispenses of a block
    get_sweeps_by_block
                        Returns the sweeps of a block
    get_transactions    Returns the list of the last ten transactions
    info                Returns Counterparty information from a raw transaction in hex format.
    unpack              Unpacks Counterparty data in hex format and returns the message type and data.
    get_transaction_by_tx_index
                        Returns a transaction by its index.
    get_transaction_by_hash
                        Returns a transaction by its hash.
    get_events_by_transaction_index
                        Returns the events of a transaction
    get_events_by_transaction_hash
                        Returns the events of a transaction
    get_sends_by_transaction_hash
                        Returns the sends, include Enhanced and MPMA sends, of a block
    get_dispenses_by_transaction_hash
                        Returns the dispenses of a block
    get_events_by_transaction_index_and_event
                        Returns the events of a transaction
    get_events_by_transaction_hash_and_event
                        Returns the events of a transaction
    get_balances_by_addresses
                        Returns the balances of several addresses
    get_transactions_by_addresses
                        Returns the transactions of a list of addresses
    get_events_by_addresses
                        Returns the events of a list of addresses
    get_mempool_events_by_addresses
                        Returns the mempool events of a list of addresses
    get_address_balances
                        Returns the balances of an address
    get_balance_by_address_and_asset
                        Returns the balance of an address and asset
    get_credits_by_address
                        Returns the credits of an address
    get_debits_by_address
                        Returns the debits of an address
    get_bet_by_feed     Returns the bets of a feed
    get_broadcasts_by_source
                        Returns the broadcasts of a source
    get_burns_by_address
                        Returns the burns of an address
    get_sends_by_address
                        Returns the sends, include Enhanced and MPMA sends, of an address
    get_receive_by_address
                        Returns the receives of an address
    get_sends_by_address_and_asset
                        Returns the sends, include Enhanced and MPMA sends, of an address and asset
    get_receive_by_address_and_asset
                        Returns the receives of an address and asset
    get_dispensers_by_address
                        Returns the dispensers of an address
    get_dispenser_by_address_and_asset
                        Returns the dispenser of an address and an asset
    get_dispenses_by_source
                        Returns the dispenses of a source
    get_dispenses_by_destination
                        Returns the dispenses of a destination
    get_dispenses_by_source_and_asset
                        Returns the dispenses of an address and an asset
    get_dispenses_by_destination_and_asset
                        Returns the dispenses of an address and an asset
    get_sweeps_by_address
                        Returns the sweeps of an address
    get_issuances_by_address
                        Returns the issuances of an address
    get_valid_assets_by_issuer
                        Returns the valid assets of an issuer
    get_transactions_by_address
                        Returns the transactions of an address
    get_dividends_distributed_by_address
                        Returns the dividends distributed by an address
    get_orders_by_address
                        Returns the orders of an address
    get_fairminters_by_address
                        Returns the fairminter by its source
    get_fairmints_by_address
                        Returns the mints by address
    get_fairmints_by_address_and_asset
                        Returns the mints by address and asset
    compose_bet         Composes a transaction to issue a bet against a feed.
    compose_broadcast   Composes a transaction to broadcast textual and numerical information to the network.
    compose_btcpay      Composes a transaction to pay for a BTC order match.
    compose_burn        Composes a transaction to burn a given quantity of BTC for XCP (on mainnet, possible between blocks 278310 and 283810; on testnet it is
                        still available).
    compose_cancel      Composes a transaction to cancel an open order or bet.
    compose_destroy     Composes a transaction to destroy a quantity of an asset.
    compose_dispenser   Opens or closes a dispenser for a given asset at a given rate of main chain asset (BTC). Escrowed quantity on open must be equal or
                        greater than give_quantity. It is suggested that you escrow multiples of give_quantity to ease dispenser operation.
    compose_dividend    Composes a transaction to issue a dividend to holders of a given asset.
    compose_issuance    Composes a transaction to Issue a new asset, issue more of an existing asset, lock an asset, reset existing supply, or transfer the
                        ownership of an asset.
    compose_mpma        Composes a transaction to send multiple payments to multiple addresses.
    compose_order       Composes a transaction to place an order on the distributed exchange.
    compose_send        Composes a transaction to send a quantity of an asset to another address.
    compose_sweep       Composes a transaction to Sends all assets and/or transfer ownerships to a destination address.
    compose_dispense    Composes a transaction to send BTC to a dispenser.
    compose_fairminter  Composes a transaction to issue a new asset using the FairMinter protocol.
    compose_fairmint    Composes a transaction to mint a quantity of an asset using the FairMinter protocol.
    compose_attach      Attach assets from an address to UTXO.
    compose_detach      Detach assets from UTXO to an address.
    compose_movetoutxo  Move assets from UTXO to another UTXO.
    get_valid_assets    Returns the valid assets
    get_asset           Returns an asset by its name
    get_asset_balances  Returns the asset balances
    get_balance_by_address_and_asset
                        Returns the balance of an address and asset
    get_orders_by_asset
                        Returns the orders of an asset
    get_order_matches_by_asset
                        Returns the orders of an asset
    get_credits_by_asset
                        Returns the credits of an asset
    get_debits_by_asset
                        Returns the debits of an asset
    get_dividends_by_asset
                        Returns the dividends of an asset
    get_issuances_by_asset
                        Returns the issuances of an asset
    get_sends_by_asset  Returns the sends, include Enhanced and MPMA sends, of an asset
    get_dispensers_by_asset
                        Returns the dispensers of an asset
    get_dispenser_by_address_and_asset
                        Returns the dispenser of an address and an asset
    get_asset_holders   Returns the holders of an asset
    get_dispenses_by_asset
                        Returns the dispenses of an asset
    get_subassets_by_asset
                        Returns asset subassets
    get_fairminters_by_asset
                        Returns the fairminter by its asset
    get_fairmints_by_asset
                        Returns the mints by asset
    get_fairmints_by_address_and_asset
                        Returns the mints by address and asset
    get_orders          Returns all the orders
    get_order           Returns the information of an order
    get_order_matches_by_order
                        Returns the order matches of an order
    get_btcpays_by_order
                        Returns the BTC pays of an order
    get_orders_by_two_assets
                        Returns the orders to exchange two assets
    get_order_matches_by_two_assets
                        Returns the orders to exchange two assets
    get_all_order_matches
                        Returns all the order matches
    get_bets            Returns the bets of a feed
    get_bet             Returns the information of a bet
    get_bet_matches_by_bet
                        Returns the bet matches of a bet
    get_resolutions_by_bet
                        Returns the resolutions of a bet
    get_all_burns       Returns the burns
    get_dispensers      Returns all dispensers
    get_dispenser_info_by_hash
                        Returns the dispenser information by tx_hash
    get_dispenses_by_dispenser
                        Returns the dispenses of a dispenser
    get_dividends       Returns all the dividends
    get_dividend        Returns a dividend by its hash
    get_dividend_disribution
                        Returns a dividend distribution by its hash
    get_all_events      Returns all events
    get_event_by_index  Returns the event of an index
    get_all_events_counts
                        Returns the event counts of all blocks
    get_events_by_name  Returns the events filtered by event name
    get_event_count     Returns the number of events
    get_dispenses       Returns all the dispenses
    get_sends           Returns all the sends include Enhanced and MPMA sends
    get_issuances       Returns all the issuances
    get_issuance_by_transaction_hash
                        Returns the issuances of a block
    get_sweeps          Returns all sweeps
    get_sweep_by_transaction_hash
                        Returns the sweeps of a transaction
    get_valid_broadcasts
                        Returns all valid broadcasts
    get_broadcast_by_transaction_hash
                        Returns the broadcast of a transaction
    get_all_fairminters
                        Returns all fairminters
    get_fairminter      Returns the fairminter by its hash
    get_fairmints_by_fairminter
                        Returns the mints by fairminter
    get_unspent_txouts_by_addresses
                        Returns a list of unspent outputs for a list of addresses
    get_transactions_by_address
                        Returns all transactions involving a given address
    get_oldest_transaction_by_address
                        Get the oldest transaction for an address.
    get_unspent_txouts  Returns a list of unspent outputs for a specific address
    pubkeyhash_to_pubkey
                        Get pubkey for an address.
    get_transaction     Get a transaction from the blockchain
    fee_per_kb          Get the fee per kilobyte for a transaction to be confirmed in `conf_target` blocks.
    sendrawtransaction  Proxy to `sendrawtransaction` RPC call.
    get_all_mempool_events
                        Returns all mempool events
    get_mempool_events_by_name
                        Returns the mempool events filtered by event name
    get_mempool_events_by_tx_hash
                        Returns the mempool events filtered by transaction hash
    get_routes          Return the API routes.
    check_server_health
                        Health check route.
    send_bet            Composes, sign and send a transaction to issue a bet against a feed.
    send_broadcast      Composes, sign and send a transaction to broadcast textual and numerical information to the network.
    send_btcpay         Composes, sign and send a transaction to pay for a BTC order match.
    send_burn           Composes, sign and send a transaction to burn a given quantity of BTC for XCP (on mainnet, possible between blocks 278310 and 283810; on
                        testnet it is still available).
    send_cancel         Composes, sign and send a transaction to cancel an open order or bet.
    send_destroy        Composes, sign and send a transaction to destroy a quantity of an asset.
    send_dispenser      Opens or closes a dispenser for a given asset at a given rate of main chain asset (BTC). Escrowed quantity on open must be equal or
                        greater than give_quantity. It is suggested that you escrow multiples of give_quantity to ease dispenser operation.
    send_dividend       Composes, sign and send a transaction to issue a dividend to holders of a given asset.
    send_issuance       Composes, sign and send a transaction to Issue a new asset, issue more of an existing asset, lock an asset, reset existing supply, or
                        transfer the ownership of an asset.
    send_mpma           Composes, sign and send a transaction to send multiple payments to multiple addresses.
    send_order          Composes, sign and send a transaction to place an order on the distributed exchange.
    send_send           Composes, sign and send a transaction to send a quantity of an asset to another address.
    send_sweep          Composes, sign and send a transaction to Sends all assets and/or transfer ownerships to a destination address.
    send_dispense       Composes, sign and send a transaction to send BTC to a dispenser.
    send_fairminter     Composes, sign and send a transaction to issue a new asset using the FairMinter protocol.
    send_fairmint       Composes, sign and send a transaction to mint a quantity of an asset using the FairMinter protocol.
    send_attach         Attach assets from an address to UTXO.
    send_detach         Detach assets from UTXO to an address.
    send_movetoutxo     Move assets from UTXO to another UTXO.

options:
  -h, --help            show this help message and exit
```

-----

* [ ] Double-check the spelling and grammar of all strings, code comments, etc.
* [ ] Double-check that all code is deterministic that needs to be
* [ ] Add tests to cover any new or revised logic
* [ ] Ensure that the test suite passes
* [ ] Update the project [release notes](release-notes/)
* [ ] Update the project documentation, as appropriate, with a corresponding Pull Request in the [Documentation repository](https://github.com/CounterpartyXCP/Documentation)

### CODE REVIEW

**Comment by ouziel-slama** [comment]
```
$ python3 tools/xcpcli.py get_asset_balances -h
usage: xcpcli get_asset_balances [-h] --asset ASSET [--cursor CURSOR] [--limit LIMIT] [--offset OFFSET] [--sort SORT] [--verbose] [--show_unconfirmed]

options:
  -h, --help          show this help message and exit
  --asset ASSET       The asset to return (e.g. $ASSET_1)
  --cursor CURSOR     The last index of the balances to return
  --limit LIMIT       The maximum number of balances to return (e.g. 5)
  --offset OFFSET     The number of lines to skip before returning results (overrides the `cursor` parameter)
  --sort SORT         The sort order of the balances to return (overrides the `cursor` parameter) (e.g. quantity:desc)
  --verbose           Include asset and dispenser info and normalized quantities in the response.
  --show_unconfirmed  Include results from Mempool.
```
--------

```
$ python3 tools/xcpcli.py get_asset_balances --asset XCP
{
    "result": [
        {
            "address": "bcrt1q0dauph4js97j00t2tg9x2fykpk2w5x8ne8g83r",
            "utxo": null,
            "utxo_address": null,
            "asset": "XCP",
            "quantity": 74999998167
        },
        {
            "address": "bcrt1q94v9par73xq4lhc2n6eaft3swjps9rh6evwtuu",
            "utxo": null,
            "utxo_address": null,
            "asset": "XCP",
            "quantity": 74999998000
        },
        {
            "address": "bcrt1qh7vh59w52usnpnsfmktqhx5c2cn8yycd2u0u27",
            "utxo": null,
            "utxo_address": null,
            "asset": "XCP",
            "quantity": 74999997833
        },
        {
            "address": "bcrt1qhh84hgrsqxv9a8uz0p8n0nn3qtne8vexfhcl0t",
            "utxo": null,
            "utxo_address": null,
            "asset": "XCP",
            "quantity": 74999997667
        },
        {
            "address": "bcrt1qkd8ws4pn6g4gzm358fprv3935836duh8whg3xf",
            "utxo": null,
            "utxo_address": null,
            "asset": "XCP",
            "quantity": 74999997500
        },
        {
            "address": "bcrt1ql37ckrm90yaut7rfyw4jdsmfz7wl6wpgpfve78",
            "utxo": null,
            "utxo_address": null,
            "asset": "XCP",
            "quantity": 74999997333
        },
        {
            "address": "bcrt1qqx3vyje4df2usgvndg2fvtj8nsnsm5dxq7a7ql",
            "utxo": null,
            "utxo_address": null,
            "asset": "XCP",
            "quantity": 74999997167
        },
        {
            "address": "bcrt1quqhzsqkhu8cgrxf9u68dju9fls7g6s24vaewy4",
            "utxo": null,
            "utxo_address": null,
            "asset": "XCP",
            "quantity": 74999997000
        },
        {
            "address": "bcrt1qusq9znaxgfn8klvw77np3tchv2g0djzf6v3zfn",
            "utxo": null,
            "utxo_address": null,
            "asset": "XCP",
            "quantity": 74999996803
        },
        {
            "address": "bcrt1qwwgz2gvm2ck9wvcycrt3py3c8um0kdpp49dlzp",
            "utxo": null,
            "utxo_address": null,
            "asset": "XCP",
            "quantity": 74999996667
        },
        {
            "address": "mjts5dr3JwF7U5MMNWkG8dYffEAXEhayFn",
            "utxo": null,
            "utxo_address": null,
            "asset": "XCP",
            "quantity": 30
        }
    ],
    "next_cursor": null,
    "result_count": 11
}
```

**Comment by ouziel-slama** [comment]
```
$ python3 tools/xcpcli.py send_send -h
usage: xcpcli send_send [-h] --address ADDRESS --destination DESTINATION --asset ASSET --quantity QUANTITY [--memo MEMO] [--memo_is_hex] [--use_enhanced_send]
                        [--encoding ENCODING] [--fee_per_kb FEE_PER_KB] [--regular_dust_size REGULAR_DUST_SIZE] [--multisig_dust_size MULTISIG_DUST_SIZE]
                        [--pubkey PUBKEY] [--allow_unconfirmed_inputs] [--fee FEE] [--fee_provided FEE_PROVIDED] [--unspent_tx_hash UNSPENT_TX_HASH]
                        [--dust_return_pubkey DUST_RETURN_PUBKEY] [--disable_utxo_locks] [--extended_tx_info] [--p2sh_pretx_txid P2SH_PRETX_TXID] [--segwit]
                        [--confirmation_target CONFIRMATION_TARGET] [--return_psbt] [--exclude_utxos EXCLUDE_UTXOS] [--return_only_data] [--verbose]
                        [--show_unconfirmed]

options:
  -h, --help            show this help message and exit
  --address ADDRESS     The address that will be sending (must have the necessary quantity of the specified asset) (e.g. $ADDRESS_1)
  --destination DESTINATION
                        The address that will be receiving the asset (e.g. $ADDRESS_2)
  --asset ASSET         The asset or subasset to send (e.g. XCP)
  --quantity QUANTITY   The quantity of the asset to send (in satoshis, hence integer) (e.g. 1000)
  --memo MEMO           The Memo associated with this transaction
  --memo_is_hex         Whether the memo field is a hexadecimal string
  --use_enhanced_send   If this is false, the construct a legacy transaction sending bitcoin dust
  --encoding ENCODING   The encoding method to use
  --fee_per_kb FEE_PER_KB
                        The fee per kilobyte of transaction data constant that the server uses when deciding on the dynamic fee to use (in satoshis)
  --regular_dust_size REGULAR_DUST_SIZE
                        Specify (in satoshis) to override the (dust) amount of BTC used for each non-(bare) multisig output.
  --multisig_dust_size MULTISIG_DUST_SIZE
                        Specify (in satoshis) to override the (dust) amount of BTC used for each (bare) multisig output
  --pubkey PUBKEY       The hexadecimal public key of the source address (or a list of the keys, if multi-sig). Required when using encoding parameter values of
                        multisig or pubkeyhash.
  --allow_unconfirmed_inputs
                        Set to true to allow this transaction to utilize unconfirmed UTXOs as inputs
  --fee FEE             If you'd like to specify a custom miners' fee, specify it here (in satoshis). Leave as default for the server to automatically choose
  --fee_provided FEE_PROVIDED
                        If you would like to specify a maximum fee (up to and including which may be used as the transaction fee), specify it here (in
                        satoshis). This differs from fee in that this is an upper bound value, which fee is an exact value
  --unspent_tx_hash UNSPENT_TX_HASH
                        When compiling the UTXOs to use as inputs for the transaction being created, only consider unspent outputs from this specific
                        transaction hash. Defaults to null to consider all UTXOs for the address. Do not use this parameter if you are specifying custom_inputs
  --dust_return_pubkey DUST_RETURN_PUBKEY
                        The dust return pubkey is used in multi-sig data outputs (as the only real pubkey) to make those the outputs spendable. By default, this
                        pubkey is taken from the pubkey used in the first transaction input. However, it can be overridden here (and is required to be specified
                        if a P2SH input is used and multisig is used as the data output encoding.) If specified, specify the public key (in hex format) where
                        dust will be returned to so that it can be reclaimed. Only valid/useful when used with transactions that utilize multisig data encoding.
                        Note that if this value is set to false, this instructs counterparty-server to use the default dust return pubkey configured at the node
                        level. If this default is not set at the node level, the call will generate an exception
  --disable_utxo_locks  By default, UTXOs utilized when creating a transaction are 'locked' for a few seconds, to prevent a case where rapidly generating
                        create_ calls reuse UTXOs due to their spent status not being updated in bitcoind yet. Specify true for this parameter to disable this
                        behavior, and not temporarily lock UTXOs
  --extended_tx_info    When this is not specified or false, the create_ calls return only a hex-encoded string. If this is true, the create_ calls return a
                        data object with the following keys: tx_hex, btc_in, btc_out, btc_change, and btc_fee
  --p2sh_pretx_txid P2SH_PRETX_TXID
                        The previous transaction txid for a two part P2SH message. This txid must be taken from the signed transaction
  --segwit              Use segwit
  --confirmation_target CONFIRMATION_TARGET
                        The number of blocks to target for confirmation
  --return_psbt         Construct a PSBT instead of a raw transaction hex
  --exclude_utxos EXCLUDE_UTXOS
                        A comma-separated list of UTXO txids to exclude when selecting UTXOs to use as inputs for the transaction being created
  --return_only_data    Return only the data part of the transaction
  --verbose             Include asset and dispenser info and normalized quantities in the response.
  --show_unconfirmed    Include results from Mempool.
```
--------
````
$ python3 tools/xcpcli.py send_send --address bcrt1qusq9znaxgfn8klvw77np3tchv2g0djzf6v3zfn --asset XCP --destination mjts5dr3JwF7U5MMNWkG8dYffEAXEhayFn --quantity 10
{
    "result": {
        "rawtransaction": "02000000000101c1bb34792130c0109e42b0179bc7c937f6c2a1e8d4b65e76505d883eb5dda78a02000000160014e400514fa642667b7d8ef7a618af176290f6c849ffffffff0322020000000000001976a91430054d418546ffbc0c73830eac288ec1e8dcc7f588ac00000000000000001e6a1c4f9cf8266efdc188e32567e8cf77d6c91803001f4171fa0ecd15bd742c6b0a2701000000160014e400514fa642667b7d8ef7a618af176290f6c84902000000000000",
        "params": {
            "source": "bcrt1qusq9znaxgfn8klvw77np3tchv2g0djzf6v3zfn",
            "destination": "mjts5dr3JwF7U5MMNWkG8dYffEAXEhayFn",
            "asset": "XCP",
            "quantity": 10,
            "memo": null,
            "memo_is_hex": false,
            "use_enhanced_send": false
        },
        "name": "send"
    }
}
Signing and sending transaction...
Transaction sent: b766ef9a27a195b190c89f1dafe758882e7c74d975a49a7750e74390c38da72e
Block mined
```

**Comment by ouziel-slama** [comment]
For now mainly to test v10.4.0 on regtest with:

```
$ python3 counterpartycore/test/regtest/regtestnode.py 
```

could be improved to be used as basic wallet for mainnet/testnet

**Review by adamkrellenstein — APPROVED** [review]
nice!

**Pull request merged**
