### PR TITLE
Add '--skip-db-check' flag

### PR DESCRIPTION
**Pull request by ouziel-slama**

### CODE REVIEW

**Comment by adamkrellenstein** [comment]
Let's just add something in the release notes for this.

**Review by adamkrellenstein — APPROVED** [review]

**Comment by adamkrellenstein** [comment]
And in the documentation.

**Comment by ouziel-slama** [comment]
> Let's just add something in the release notes for this.

done!

**Comment by ouziel-slama** [comment]
> And in the documentation.

see https://github.com/CounterpartyXCP/Documentation/pull/189

**Pull request merged**
