### PR TITLE
`SimpleNode` is just Docker Compose 🙄

### PR DESCRIPTION
**Pull request by adamkrellenstein**

### CODE REVIEW

**Comment by ouziel-slama** [comment]
Do we really need the sub folders with config file ?

**Comment by adamkrellenstein** [comment]
I think we need the `bitcoind` one? but the counterparty config files can probably just be examples in the docs

**Comment by ouziel-slama** [comment]
> I think we need the `bitcoind` one? but the counterparty config files can probably just be examples in the docs

hum.. I think we need it only if we want to maintain a `counterparty/bitcoind` image with this default configuration else the parameters in `compose.yml` should be enough.

**Comment by adamkrellenstein** [comment]
Ah yes, I forget why I did that! I think I just wanted people to be able run the bitcoind in docker without docker compose?? but there's probably no reason for that.

We can get rid of our bitcoind image.

**Pull request merged**
